name: codecipher triage
on:
  issues:
    types: [opened]
jobs:
  commentOnNewIssues:
    name: codecipher triage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: codecipher triage
        uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: comment "[codecipher] should be supported for Python 3.7, 3.8, 3.9"
